# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aoikida/Desktop/anti-entropy/distributed_kv_store

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aoikida/Desktop/anti-entropy/distributed_kv_store

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aoikida/Desktop/anti-entropy/distributed_kv_store/CMakeFiles /Users/aoikida/Desktop/anti-entropy/distributed_kv_store//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aoikida/Desktop/anti-entropy/distributed_kv_store/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kv_store_lib

# Build rule for target.
kv_store_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kv_store_lib
.PHONY : kv_store_lib

# fast build rule for target.
kv_store_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store_lib.dir/build.make CMakeFiles/kv_store_lib.dir/build
.PHONY : kv_store_lib/fast

#=============================================================================
# Target rules for targets named node1

# Build rule for target.
node1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 node1
.PHONY : node1

# fast build rule for target.
node1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node1.dir/build.make CMakeFiles/node1.dir/build
.PHONY : node1/fast

#=============================================================================
# Target rules for targets named node2

# Build rule for target.
node2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 node2
.PHONY : node2

# fast build rule for target.
node2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node2.dir/build.make CMakeFiles/node2.dir/build
.PHONY : node2/fast

anti_entropy/anti_entropy_manager.o: anti_entropy/anti_entropy_manager.cpp.o
.PHONY : anti_entropy/anti_entropy_manager.o

# target to build an object file
anti_entropy/anti_entropy_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store_lib.dir/build.make CMakeFiles/kv_store_lib.dir/anti_entropy/anti_entropy_manager.cpp.o
.PHONY : anti_entropy/anti_entropy_manager.cpp.o

anti_entropy/anti_entropy_manager.i: anti_entropy/anti_entropy_manager.cpp.i
.PHONY : anti_entropy/anti_entropy_manager.i

# target to preprocess a source file
anti_entropy/anti_entropy_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store_lib.dir/build.make CMakeFiles/kv_store_lib.dir/anti_entropy/anti_entropy_manager.cpp.i
.PHONY : anti_entropy/anti_entropy_manager.cpp.i

anti_entropy/anti_entropy_manager.s: anti_entropy/anti_entropy_manager.cpp.s
.PHONY : anti_entropy/anti_entropy_manager.s

# target to generate assembly for a file
anti_entropy/anti_entropy_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store_lib.dir/build.make CMakeFiles/kv_store_lib.dir/anti_entropy/anti_entropy_manager.cpp.s
.PHONY : anti_entropy/anti_entropy_manager.cpp.s

node.o: node.cpp.o
.PHONY : node.o

# target to build an object file
node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store_lib.dir/build.make CMakeFiles/kv_store_lib.dir/node.cpp.o
.PHONY : node.cpp.o

node.i: node.cpp.i
.PHONY : node.i

# target to preprocess a source file
node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store_lib.dir/build.make CMakeFiles/kv_store_lib.dir/node.cpp.i
.PHONY : node.cpp.i

node.s: node.cpp.s
.PHONY : node.s

# target to generate assembly for a file
node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store_lib.dir/build.make CMakeFiles/kv_store_lib.dir/node.cpp.s
.PHONY : node.cpp.s

node1.o: node1.cpp.o
.PHONY : node1.o

# target to build an object file
node1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node1.dir/build.make CMakeFiles/node1.dir/node1.cpp.o
.PHONY : node1.cpp.o

node1.i: node1.cpp.i
.PHONY : node1.i

# target to preprocess a source file
node1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node1.dir/build.make CMakeFiles/node1.dir/node1.cpp.i
.PHONY : node1.cpp.i

node1.s: node1.cpp.s
.PHONY : node1.s

# target to generate assembly for a file
node1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node1.dir/build.make CMakeFiles/node1.dir/node1.cpp.s
.PHONY : node1.cpp.s

node2.o: node2.cpp.o
.PHONY : node2.o

# target to build an object file
node2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node2.dir/build.make CMakeFiles/node2.dir/node2.cpp.o
.PHONY : node2.cpp.o

node2.i: node2.cpp.i
.PHONY : node2.i

# target to preprocess a source file
node2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node2.dir/build.make CMakeFiles/node2.dir/node2.cpp.i
.PHONY : node2.cpp.i

node2.s: node2.cpp.s
.PHONY : node2.s

# target to generate assembly for a file
node2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node2.dir/build.make CMakeFiles/node2.dir/node2.cpp.s
.PHONY : node2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kv_store_lib"
	@echo "... node1"
	@echo "... node2"
	@echo "... anti_entropy/anti_entropy_manager.o"
	@echo "... anti_entropy/anti_entropy_manager.i"
	@echo "... anti_entropy/anti_entropy_manager.s"
	@echo "... node.o"
	@echo "... node.i"
	@echo "... node.s"
	@echo "... node1.o"
	@echo "... node1.i"
	@echo "... node1.s"
	@echo "... node2.o"
	@echo "... node2.i"
	@echo "... node2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

